Add sensor mediation HAL
projectceladon/sensor-mediation pull request #2
Opened 2020-06-08 14:02 UTC by JaikrishnaNemallapudi

Initial Release code

Tracked-On: OAM-91265
Signed-off-by: Jaikrishna Nemallapudi <nemallapudi.jaikrishna@intel.com>

2020-06-08 16:56 UTC, sysopenci reviewed
Autobuild started from pull-request-changes on this PR.

Cactus automatically verified this PR.

For more information, see: /absp/builders/celadon-autobuild/builds/2219

2020-06-08 17:57 UTC, rbabub approved these changes
Looks good to me.

2020-06-08 18:13 UTC, JeevakaPrabu requested changes

2020-06-08 18:13 UTC, JeevakaPrabu commented on sensor_hal.cpp
> + * Copyright Copyright (c) 2020 Intel Corporation
Remove 1 Copyright

2020-06-09 03:48 UTC, JaikrishnaNemallapudi commented on sensor_hal.cpp
> + * Copyright Copyright (c) 2020 Intel Corporation
Fixed the duplicate string

2020-06-09 07:10 UTC, rbabub approved these changes
Looks good to me.

2020-06-09 09:58 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2028

2020-06-09 10:42 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2029

2020-06-09 16:04 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds cancelled

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2031

2020-06-09 20:05 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2032

Done by "Jaikrishna, Nemallapudi" <nemallapudi.jaikrishna@intel.com>

2020-06-09 20:06 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/1038

Done by "Jaikrishna, Nemallapudi" <nemallapudi.jaikrishna@intel.com>

2020-06-09 22:12 UTC, merged

2020-06-09 22:13 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Jaikrishna, Nemallapudi" <nemallapudi.jaikrishna@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon-mergerequest/builds/1744